
SELECT gr.[GROUP_ID] , gr.[NAME], COUNT(st.[GROUP_ID]) AS STUDENTS_COUNT
FROM [dbo].[STUDENTS] st  LEFT JOIN [dbo].[GROUPS] gr ON gr.[GROUP_ID] = st.[GROUP_ID]

GROUP BY gr.[GROUP_ID] , gr.[NAME]
HAVING COUNT(st.[GROUP_ID]) < 10
